UniversityDatabase/Controllers/DeanController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using UniversityDatabase.Data;
using UniversityDatabase.Models;
using UniversityDatabase.ViewModels.Dean;

namespace UniversityDatabase.Controllers
{
    public class DeanController : Controller
    {
        private MyDbContext _dbContext;

        public DeanController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public ActionResult Index()
        {
            var deansList = _dbContext.Deans.ToList();

            var deanViewModel = new DeanIndexViewModel { Deans = deansList };

            return View(deanViewModel);
        }

        public ActionResult Create()
        {
            var deanViewModel = new DeanCreateViewModel();
            return View(deanViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dean dean)
        {
            
            try
            {
                _dbContext.Deans.Add(dean);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                TempData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Edit(int id)
        {
           
            try
            {
                var dean = _dbContext.Deans.First(d=> d.Id == id);

                var deanViewModel = new DeanCreateViewModel { Dean = dean };

                return View(deanViewModel);
            }
            catch (Exception e)
            {

                TempData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Dean dean)
        {
            
            try
            {
                _dbContext.Deans.Update(dean);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                TempData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }


        // POST: DeanController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var dean = _dbContext.Deans.First(d=>d.Id==id);

                _dbContext.Deans.Remove(dean);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                TempData["error"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

UniversityDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityDatabase</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityDatabase.styles.css" asp-append-version="true" />
</head>
<body>
    @if(TempData["error"] != null){
        <div class="alert">@TempData["error"]</div>
    }
    <header class="header">
        <div class="container">
            <nav class="nav">
                <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <img asp-append-version class="logo__img" src="~/content/logo.svg"/>
                </a>
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Dean" asp-action="Index">Деканаты</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Faculty" asp-action="Index">Факультеты</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Department" asp-action="Index">Кафедры</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="StudyGroup" asp-action="Index">Учебные группы</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Student" asp-action="Index">Студенты</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Teacher" asp-action="Index">Преподаватели</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="StudyPlan" asp-action="Index">Учебный план</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="StudentGrade" asp-action="Index">Оценки</a>
                        </li>
                        <li class="nav__item">
                            <a class="nav__link" asp-area="" asp-controller="Workload" asp-action="Index">Нагрузка</a>
                        </li>
                    </ul>
        </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            &copy; 2023 - UniversityDatabase
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>